kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: image-registry-storage 
  namespace: openshift-image-registry 
spec:
  storageClassName: openshift-storage.cephfs.csi.ceph.com
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
